### ISSUE TITLE
Error spam - filtering?

### ISSUE THREAD

**Issue by eileenmcnaughton** [mlutfy/ca.bidon.reporterror#11]
Hi,

I'm getting LOADS of these "The page you requested is currently unavailable" which makes me not want to role this out further. I'm wondering it the Error module should allow site administrators to filter specific strings - do you think that would be the right approach?

**Comment by mlutfy** [comment]
Most of these things have been implemented, ex: accessing a contribution page without a proper referer, and filtering bots (in v2.8 released today).
