### ISSUE TITLE
incorrect URL when installed

### ISSUE THREAD

**Issue by Upperholme** [mlutfy/ca.bidon.reporterror#15]
Hi.
when i install the extension it gives the following URL as the link for documentation:
https://github.com/mlutfy/ca.bidon.reporterror/blob/master/README.txt
which doesn't work
I'm thinking perhaps it should be 
https://github.com/mlutfy/ca.bidon.reporterror/blob/master/README.md ?

**Comment by mlutfy** [comment]
Yikes, sorry it took a year to fix this trivial issue. Thanks for the report nonetheless!
