### ISSUE TITLE
Latest code says version 2.7 is available

### ISSUE THREAD

**Issue by magnolia61** [mlutfy/ca.bidon.reporterror#17]
Is that a mistake? From what I see 2.5 is your latest release.

**Comment by mlutfy** [comment]
Hmm, I had forgotten to create a release here on github, so it was not showing properly in the list of releases (we had to click on the text "show 2 more releases"). Thanks for pointing that out!

You can also see the release here: https://civicrm.org/extensions/civicrm-error-handler
