### ISSUE TITLE
settings page shows Admin Console

### ISSUE THREAD

**Issue by twomice** [mlutfy/ca.bidon.reporterror#20]
After installing this extension, I navigate to Administer > System Settings > Report Error Settings (/civicrm/admin/setting/reporterror?reset=1), and instead of a settings page, I see the CiviCRM Admin Console (same page as at /civicrm/admin?reset=1)

This is CiviCRM 4.4.17.

**Comment by mlutfy** [comment]
Hmm, that's odd. Did you install from the Extension Manager (if yes, which version?) or from git? (master?)

Just to double-check, can you run a system.flush/clear cache on CiviCRM? (drush cvapi system.flush)

**Comment by twomice** [comment]
OK, looks like that fixed it (drush cvapi system.flush).  BTW, this was installed from the Extension Manager, which installed version 2.8

Thanks!

**Comment by mlutfy** [comment]
Thanks for the update.

From what I see at a quick glance, CRM_Extension_Manage calls "CRM_Core_Invoke::rebuildMenuAndCaches()" during the installation of an extension (checked 4.4 and 4.6). If you repeatedly run into this bug, don't hesitate to re-open the issue.
