### ISSUE TITLE
Uninstall doesn't work on 4.7.11

### ISSUE THREAD

**Issue by michaelmcandrew** [mlutfy/ca.bidon.reporterror#21]
Hey there,

I'm not sure when the group_name was removed from the civicrm_setting file but it is causing the uninstall to fail (https://github.com/mlutfy/ca.bidon.reporterror/blob/master/reporterror.php#L61)

I had a look for a delete method in CRM_Core_BAO_Setting and in the Setting api but coudn't find one. Which I presume is the reason you didn't use it :)

But it seems like you have a valid reason for deleting settings, so...

**Comment by mlutfy** [comment]
That code was written back in the 4.2 days, so yep, it should probably be updated. :-)
Thanks for reporting the issue!

**Comment by michaelmcandrew** [comment]
np :)

**Comment by mlutfy** [comment]
This should be fixed. It's not a great fix, but it  works :)
