### ISSUE TITLE
CiviCRM 4.7: Default settings should come from metadata

### ISSUE THREAD

**Issue by magnolia61** [mlutfy/ca.bidon.reporterror#22]
With php7 support for civicrm now, I think this has to to with that? Not much of a coder myself, but thought I let you know this message from the debuglog.

Nov 15 23:35:14  [info] Deprecated: Group='ReportError Extension'. Name='noreferer_sendreport_event'. Defaults should come from metadata

**Comment by mlutfy** [comment]
Hmm, this is because CiviCRM changed how default setting values are defined in CiviCRM 4.7. It's not really a big issue, but I understand that I can be noisy in the logs.

**Comment by mlutfy** [comment]
Fixed in 7316499eacfd4e365a5ce6488cfa755b2f0dd8e1
