### ISSUE TITLE
Failed to Open Stream No Such Directory

### ISSUE THREAD

**Issue by frerghost** [mlutfy/ca.bidon.reporterror#37]
WordPress v6.4.3 CiviCRM v5.71.1 PHP v8.1

So, upgraded CiviCRM and the Report Error Extension today and ended up with the below. I had to roll everything back, re-update, and delete the Extension. 

`Warning: require_once(/home/xxxxxxxxx/public_html/wp-content/uploads/civicrm/ext/ca.bidon.reporterror/vendor/autoload.php): Failed to open stream: No such file or directory in /home/xxxxxxxxx/public_html/wp-content/uploads/civicrm/ext/ca.bidon.reporterror/reporterror.php on line 8

Fatal error: Uncaught Error: Failed opening required '/home/xxxxxxxxx/public_html/wp-content/uploads/civicrm/ext/ca.bidon.reporterror/vendor/autoload.php' (include_path='.:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/tecnickcom:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/pear_exception:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/auth_sasl:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/console_getopt:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/db:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/log:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/mail:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/mail_mime:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/net_socket:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/net_smtp:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/pear/validate_finance_creditcard:.:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/:/home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm//packages:.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/xxxxxxxxx/public_html/wp-content/uploads/civicrm/ext/ca.bidon.reporterror/reporterror.php:8 Stack trace: #0 /home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(324): include_once() #1 /home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(221): CRM_Utils_Hook->requireCiviModules() #2 /home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/Container.php(690): CRM_Utils_Hook->commonBuildModuleList() #3 /home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Config.php(87): Civi\Core\Container::boot() #4 /home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/includes/civicrm.admin.php(444): CRM_Core_Config::singleton() #5 /home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm.php(1002): CiviCRM_For_WordPress_Admin->initialize() #6 /home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm.php(824): CiviCRM_For_WordPress->initialize() #7 /home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm.php(797): CiviCRM_For_WordPress->register_hooks_clean_urls() #8 /home/xxxxxxxxx/public_html/wp-content/plugins/civicrm/civicrm.php(681): CiviCRM_For_WordPress->register_hooks_common() #9 /home/xxxxxxxxx/public_html/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->register_hooks() #10 /home/xxxxxxxxx/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #11 /home/xxxxxxxxx/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #12 /home/xxxxxxxxx/public_html/wp-settings.php(643): do_action() #13 /home/xxxxxxxxx/public_html/wp-config.php(88): require_once('/home/xxxxxxxxx/...') #14 /home/xxxxxxxxx/public_html/wp-load.php(50): require_once('/home/xxxxxxxxx/...') #15 /home/xxxxxxxxx/public_html/wp-blog-header.php(13): require_once('/home/xxxxxxxxx/...') #16 /home/xxxxxxxxx/public_html/index.php(17): require('/home/xxxxxxxxx/...') #17 {main} thrown in /home/xxxxxxxxx/public_html/wp-content/uploads/civicrm/ext/ca.bidon.reporterror/reporterror.php on line 8`

**Comment by mlutfy** [comment]
@frerghost see: https://lab.civicrm.org/extensions/reporterror/-/issues/7#note_162213
